---
version: 0.2
phases:
  pre_build:
    commands:
      - echo $WEBSITE_BUCKET
      - echo $CLOUDFRONT_ID
  build:
    commands:
      - echo -e Build started on `date`
      - zip -qr site.zip ./*
      - aws s3 cp site/ s3://$WEBSITE_BUCKET --recursive
  post_build:
    commands:
      - echo -e Invalidating CACHE started on `date`
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths '/*'
artifacts:
  files:
    - site.zip